//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeraWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigo_usuario { get; set; }
        public string nombre { get; set; }
        public int codigo_cargo { get; set; }
        public Nullable<int> id_country { get; set; }
        public Nullable<int> id_city { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual city city { get; set; }
        public virtual country country { get; set; }
    }
}
